#!/usr/bin/env python
"""Rename sickle's superseded products to {basename}_stale_{datemade}.{ext}.

sickle carries TWO complete lineages of every frame, and which one is live flips
per filter (destreak_policy.SICKLE_SHORTWAVE_FILTERS):

    F187N, F210M      live: destreak_o007_crf     stale: align_o007_crf
    F335M, F470N,     live: align_o007_crf        stale: destreak_o007_crf
    F480M

Both sit in the same directory with nothing on disk saying which is which. A
cataloging run is pointed at one lineage by a single --each-suffix, so the wrong
value silently photometers the other one.

Renaming inserts ``_stale_<YYYYMMDD>`` before the extension. Every pipeline glob
is anchored on a fixed trailing token (``_crf.fits``, ``_daophot_basic.fits``,
``{suffix}.fits``), so a renamed file stops matching all of them.

Dry run by default.
"""
import argparse
import os
import re
import sys
from collections import Counter
from datetime import datetime

BASE = "/orange/adamginsburg/jwst/sickle"

#: filter -> the crf lineage token that is LIVE for it.  From
#: jwst_gc_pipeline.reduction.destreak_policy: sickle's short-wavelength filters
#: destreak, its long-wavelength filters stay on the plain aligned copy.
LIVE = {
    "F187N": "destreak_o007_crf",
    "F210M": "destreak_o007_crf",
    "F335M": "align_o007_crf",
    "F470N": "align_o007_crf",
    "F480M": "align_o007_crf",
}
OTHER = {"destreak_o007_crf": "align_o007_crf",
         "align_o007_crf": "destreak_o007_crf"}

#: The un-suffixed Image3 INPUT for each lineage.  These are regenerated by every
#: reduce, so the stale-lineage one is a leftover of the same age as its crf.
INPUT_OF = {"destreak_o007_crf": "_destreak.fits",
            "align_o007_crf": "_align.fits"}

#: Filters held back from renaming, with the reason.
#:
#: The SICKLE_SHORTWAVE_FILTERS rule landed 2026-07-31 (commit de06c3b). Before
#: it, sickle was uniformly ``align`` -- it sits in EXTENDED_EMISSION_FIELDS -- so
#: F187N/F210M's align products (2026-06-15 frames, 2026-07-27/28 catalogs) are
#: the LAST GOOD short-wavelength products, made under the previous policy.
#:
#: The only destreak products those two filters have are from the 2026-08-04 run
#: that issue #270 showed produced crf which were stale copies carrying the old
#: GNS pointing. So for the short-wavelength half the "live" lineage currently
#: holds corrupt files and the "stale" lineage holds the last trustworthy ones.
#: Renaming there would leave F187N/F210M with nothing good.
#:
#: Clear these once a clean re-reduce has produced real destreak products.
HOLD = {
    "F187N": ("align products are the last good SW frames (pre-2026-07-31 "
              "policy); the only destreak products are the corrupt #270 run"),
    "F210M": ("align products are the last good SW frames (pre-2026-07-31 "
              "policy); the only destreak products are the corrupt #270 run"),
}

STALE_RE = re.compile(r"_stale_\d{8}(\.[A-Za-z0-9.]+)$")


def is_already_stale(name):
    return bool(STALE_RE.search(name))


def stale_name(name, mtime):
    """``foo_bar.fits`` -> ``foo_bar_stale_20260615.fits``.

    Splits on the FIRST dot of the extension so ``.cat.ecsv`` survives intact.
    """
    stamp = datetime.fromtimestamp(mtime).strftime("%Y%m%d")
    for ext in (".cat.ecsv", ".ecsv", ".fits", ".json", ".reg", ".png"):
        if name.endswith(ext):
            return f"{name[:-len(ext)]}_stale_{stamp}{ext}"
    root, ext = os.path.splitext(name)
    return f"{root}_stale_{stamp}{ext}"


def plan_filter(filt, verbose=True):
    """Every file in this filter's pipeline dir belonging to the stale lineage."""
    live = LIVE[filt]
    stale_tok = OTHER[live]
    stale_input = INPUT_OF[stale_tok]
    d = os.path.join(BASE, filt, "pipeline")
    if not os.path.isdir(d):
        return []

    out = []
    dates = Counter()
    with os.scandir(d) as it:
        for e in it:
            if not e.is_file():
                continue
            n = e.name
            if is_already_stale(n):
                continue
            # the stale crf lineage and everything derived from it (the derived
            # products carry the lineage token in their own names)
            hit = stale_tok in n
            # ... and the stale lineage's un-suffixed Image3 input
            if not hit and n.endswith(stale_input):
                hit = True
            if not hit:
                continue
            st = e.stat()
            out.append((e.path, stale_name(n, st.st_mtime), st.st_mtime))
            dates[datetime.fromtimestamp(st.st_mtime).strftime("%Y-%m-%d")] += 1

    if verbose:
        print(f"  {filt}: live={live}  stale={stale_tok}  -> {len(out)} file(s)")
        for day, n in sorted(dates.items()):
            print(f"      {day}: {n}")
    return out


def guard_live_lineage(filt):
    """Refuse if the lineage we are about to KEEP has no files.

    Getting LIVE backwards for a filter would rename away the only real data.
    The live lineage must exist and must not be older than the stale one.
    """
    d = os.path.join(BASE, filt, "pipeline")
    live, stale = LIVE[filt], OTHER[LIVE[filt]]
    newest = {live: 0.0, stale: 0.0}
    count = {live: 0, stale: 0}
    with os.scandir(d) as it:
        for e in it:
            if not e.is_file() or is_already_stale(e.name):
                continue
            for tok in (live, stale):
                if e.name.endswith(f"{tok}.fits"):
                    count[tok] += 1
                    newest[tok] = max(newest[tok], e.stat().st_mtime)
    if count[live] == 0:
        raise SystemExit(
            f"REFUSING {filt}: the lineage marked live ({live}) has no crf on "
            f"disk, but {stale} has {count[stale]}. LIVE is probably backwards "
            f"for this filter -- renaming would hide the only real data.")
    if newest[stale] > newest[live]:
        raise SystemExit(
            f"REFUSING {filt}: {stale} (marked stale) is NEWER than {live} "
            f"(marked live) -- "
            f"{datetime.fromtimestamp(newest[stale]):%Y-%m-%d} vs "
            f"{datetime.fromtimestamp(newest[live]):%Y-%m-%d}. Check "
            f"destreak_policy before renaming anything.")
    print(f"  {filt}: live {live} n={count[live]} "
          f"({datetime.fromtimestamp(newest[live]):%Y-%m-%d}), "
          f"stale {stale} n={count[stale]} "
          f"({datetime.fromtimestamp(newest[stale]):%Y-%m-%d}) -- OK")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true",
                    help="rename (default is a dry run)")
    ap.add_argument("--filters", default=",".join(LIVE),
                    help="comma-separated subset")
    ap.add_argument("--force-held", action="store_true",
                    help="rename a filter listed in HOLD anyway. Read its reason "
                         "first -- there the STALE lineage holds the good files.")
    args = ap.parse_args(argv)
    filters = [f.strip().upper() for f in args.filters.split(",") if f.strip()]

    if not args.force_held:
        for filt in list(filters):
            if filt in HOLD:
                print(f"HOLD {filt}: {HOLD[filt]}")
                filters.remove(filt)
        if not filters:
            print("nothing to do -- every requested filter is held.")
            return 0

    print("\nchecking the live/stale assignment against what is on disk:")
    for filt in filters:
        guard_live_lineage(filt)

    print("\nplan:")
    plans = {filt: plan_filter(filt) for filt in filters}
    total = sum(len(v) for v in plans.values())

    if not args.apply:
        print(f"\nDRY RUN -- {total} file(s) would be renamed. "
              f"Re-run with --apply.")
        return 0

    done = 0
    for filt, items in plans.items():
        for src, newname, _ in items:
            dst = os.path.join(os.path.dirname(src), newname)
            if os.path.exists(dst):
                raise SystemExit(f"REFUSING: {dst} already exists")
            os.rename(src, dst)
            done += 1
        print(f"  {filt}: renamed {len(items)}")
    print(f"\nrenamed {done} file(s).")

    # verify: nothing of the stale lineage answers a pipeline-shaped glob now
    import glob as _g
    leaks = []
    for filt in filters:
        stale_tok = OTHER[LIVE[filt]]
        pat = f"{BASE}/{filt}/pipeline/*{stale_tok}.fits"
        leaks += _g.glob(pat)
    if leaks:
        raise SystemExit(f"VERIFY FAILED: {len(leaks)} stale file(s) still match "
                         f"a *_crf.fits glob, e.g. {leaks[0]}")
    print("verify: no stale file matches a *_<lineage>.fits glob")
    return 0


if __name__ == "__main__":
    sys.exit(main())
