"""The beautified, hand-made colour images -- the ones a reader should see first.

These are NOT generated by `make_preview_rgb`.  They are the curated renders the
survey publishes elsewhere (HiPS layers, press images), and they are better than
anything the automatic planner produces: the stretches are tuned per field, the
channel choices are deliberate, and the footprints are handled correctly.

The index is `avm_images/rebuild_jwst_cmz_hips.py`, which lists the layers that
go into the published CMZ HiPS.  This registry mirrors those lists plus the
fields outside the CMZ (w51, wd2), so the release page and the HiPS show the
same pictures.  **Keep it in sync with that script.**

Three things the layer list encodes that the automatic planner gets wrong:

* **brick's two programs are combined separately.**  `Brick_RGB_444-356-200` is
  1182's wide filters, `BrickJWST_merged_longwave_narrowband` is 2221's narrow
  ones.  Crossing them makes an ugly footprint, because the two programs do not
  cover the same sky.
* **Cloud C's MIRI is two separate grayscale fields**, F2550W from 2221 and
  F770W from 2526, at different pointings.  Combining them into one RGB was
  wrong: reprojecting one onto the other's grid crops it to a corner.
* **channels are chosen far apart** -- 480/405/187, 444/356/200, 323/avg/212 --
  not adjacent.  Adjacent bands make a grey image.  Reusing a band across two
  images is better than forcing a synthetic `mean` channel.
"""
import os

AVM = "/blue/adamginsburg/adamginsburg/repos/avm_images"
GC2211_PNGS = "/orange/adamginsburg/jwst/gc2211/pngs"


def _avm(name):
    return os.path.join(AVM, name + "_transparent.png")


#: field -> curated images, best first.  ``label`` is what the caption says;
#: ``pointing`` distinguishes spatially separate images of one field.
CURATED = {
    "brick": [
        {"file": _avm("Brick_RGB_444-356-200"),
         "label": "R=F444W, G=F356W, B=F200W (JWST 1182, wide)"},
        {"file": _avm("BrickJWST_merged_longwave_narrowband"),
         "label": "long-wave narrowband (JWST 2221)"},
        {"file": _avm("Brick_RGB_1500-1130-770"),
         "label": "R=F1500W, G=F1130W, B=F770W (MIRI)", "instrument": "MIRI"},
    ],
    "sgrb2": [
        {"file": _avm("SgrB2_RGB_480-405-187_scaled"),
         "label": "R=F480M, G=F405N, B=F187N"},
        {"file": _avm("SgrB2_RGB_2550-1280-770"),
         "label": "R=F2550W, G=F1280W, B=F770W (MIRI)", "instrument": "MIRI"},
    ],
    "cloudc": [
        {"file": _avm("cloudcJWST_merged_R-F466N_B-F405N_rotated"),
         "label": "R=F466N, B=F405N"},
        # NOT one RGB: different pointings, different programs.  Reprojecting
        # one onto the other's grid crops it to a corner.
        {"file": _avm("CloudC_MIRI_F770W"),
         "label": "F770W (MIRI, JWST 2526)", "instrument": "MIRI",
         "pointing": "MIRI F770W"},
        {"file": _avm("CloudC_MIRI_F2550W"),
         "label": "F2550W (MIRI, JWST 2221)", "instrument": "MIRI",
         "pointing": "MIRI F2550W"},
    ],
    "cloudef": [
        {"file": _avm("Cloudef_RGB_4802-3602-2102"),
         "label": "R=F480M, G=F360M, B=F210M"},
    ],
    "sgrc": [
        {"file": _avm("SGRC_RGB_480-360-212"),
         "label": "R=F480M, G=F360M, B=F212N"},
        {"file": _avm("SGRC_NIRISS_RGB_480-356-200"),
         "label": "R=F480M, G=F356W, B=F200W (NIRISS parallel)",
         "instrument": "NIRISS", "pointing": "NIRISS parallel"},
    ],
    "arches": [
        {"file": _avm("ArchesQuintuplet_RGB_323-average-212_log"),
         "label": "R=F323N, G=mean, B=F212N"},
    ],
    "quintuplet": [
        {"file": _avm("Quintuplet_RGB_323-average-212_log"),
         "label": "R=F323N, G=mean, B=F212N"},
    ],
    "sgra": [
        {"file": _avm("SgrA_RGB_NIRCam_444-323-212"),
         "label": "R=F444W, G=F323N, B=F212N"},
        {"file": _avm("SgrA_RGB_MIRI_1500-1000-560"),
         "label": "R=F1500W, G=F1000W, B=F560W (MIRI)", "instrument": "MIRI"},
    ],
    "sickle": [
        {"file": _avm("Sickle_RGB_1500-1130-770"),
         "label": "R=F1500W, G=F1130W, B=F770W (MIRI)", "instrument": "MIRI"},
    ],
    "w51": [
        {"file": _avm("w51_RGB_480-405-187_scaled"), "label": "R=F480M, G=F405N, B=F187N"},
        {"file": _avm("w51_RGB_405-360-335"), "label": "R=F405N, G=F360M, B=F335M"},
        {"file": _avm("w51_RGB_360-335-210"), "label": "R=F360M, G=F335M, B=F210M"},
        {"file": _avm("w51_RGB_182-162-140_log"), "label": "R=F182M, G=F162M, B=F140M"},
        {"file": _avm("w51_RGB_162-210-187"), "label": "R=F162M, G=F210M, B=F187N"},
        {"file": _avm("w51_RGB_480-410-405"), "label": "R=F480M, G=F410M, B=F405N"},
    ],
    "wd2": [
        {"file": _avm("wd2_nircam_RGB_212-200-187_asinh_max99"),
         "label": "R=F212N, G=F200W, B=F187N"},
        {"file": _avm("wd2_nircam_RGB_410-405-335_asinh_max99.5"),
         "label": "R=F410M, G=F405N, B=F335M"},
        {"file": _avm("wd2_RGB_1000-770-410_asinh_max99.5"),
         "label": "R=F1000W, G=F770W, B=F410M (MIRI + NIRCam)"},
        {"file": _avm("wd2_RGB_1130-770-164162_sub_asinh_max99.5"),
         "label": "R=F1130W, G=F770W, B=F164N-F162M"},
        {"file": _avm("wd2_miri_RGB_1130-1000-770_log"),
         "label": "R=F1130W, G=F1000W, B=F770W (MIRI)", "instrument": "MIRI"},
    ],
    # gc2211 is five separate pointings; each has its own curated render.
    "gc2211": [
        {"file": f"{GC2211_PNGS}/o023/GC2211_o023_F277_asinh.png",
         "label": "F277W", "pointing": "o023"},
        {"file": f"{GC2211_PNGS}/o028/GC2211_o028_RGB_277-mean-150_asinh.png",
         "label": "R=F277W, G=mean, B=F150W", "pointing": "o028"},
        {"file": f"{GC2211_PNGS}/o046/GC2211_o046_RGB_277-mean-200_asinh.png",
         "label": "R=F277W, G=mean, B=F200W", "pointing": "o046"},
        {"file": f"{GC2211_PNGS}/o049/GC2211_o049_RGB_277-mean-200_asinh.png",
         "label": "R=F277W, G=mean, B=F200W", "pointing": "o049"},
        {"file": f"{GC2211_PNGS}/o050/GC2211_o050_RGB_277-mean-200_asinh.png",
         "label": "R=F277W, G=mean, B=F200W", "pointing": "o050"},
    ],
}


def for_field(field):
    """Curated images that exist on disk, best first."""
    return [dict(entry, stem=os.path.splitext(os.path.basename(entry["file"]))[0])
            for entry in CURATED.get(field, [])
            if os.path.isfile(entry["file"])]


def missing(field):
    """Registry entries whose file is not on disk -- a rename upstream."""
    return [e["file"] for e in CURATED.get(field, [])
            if not os.path.isfile(e["file"])]


def caption(entry):
    where = entry.get("pointing")
    return f"{where} - {entry['label']}" if where else entry["label"]
